import { createFileRoute, Link } from "@tanstack/react-router";
import { LogoMark } from "@/components/Logo";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — SelfeConnect" },
      { name: "description", content: "SelfeConnect terms & conditions." },
    ],
  }),
  component: Terms,
});

// Wording supplied by the client. Held as data so the page renders uniformly
// and a future revision is a single edit here rather than in the markup.
const SECTIONS: { title: string; paragraphs: string[] }[] = [
  {
    title: "1. About SelfeConnect",
    paragraphs: [
      "SelfeConnect is an online technology platform that connects customers, businesses and independent professionals. Customers can create an account, publish jobs and connect directly with local Professionals. Professionals can create profiles, browse available jobs, connect with Customers and, as an optional feature, receive cashless customer tips and payments through their personal QR code using Stripe Connect.",
      "SelfeConnect only provides the technology that enables these connections. SelfeConnect is not an employer, recruitment agency, staffing agency, contractor, broker, or party to any agreement between Customers and Professionals. Any agreement, negotiation, or business relationship exists solely between the Customer and the Professional.",
      "By creating an account or using the platform, you agree to these Terms & Conditions.",
    ],
  },
  {
    title: "2. Customer Accounts",
    paragraphs: [
      "Customers may create an account free of charge. Customers may publish job opportunities and communicate directly with Professionals. Customers are responsible for ensuring that all information they provide is accurate, lawful and up to date.",
      "SelfeConnect does not endorse or recommend any Professional. Customers remain solely responsible for selecting, verifying and engaging any Professional.",
    ],
  },
  {
    title: "3. Professional Accounts & Subscription",
    paragraphs: [
      "Professionals subscribe to SelfeConnect on a monthly basis. The first 100 professionals to subscribe pay a founding-member rate of £5.49 per month and keep that rate for as long as their subscription remains active. Professionals subscribing after those places are taken pay £9.49 per month. The price that applies to you is shown before you complete checkout.",
      "Subscriptions renew automatically until cancelled. Professionals may cancel at any time.",
      "The subscription provides access to the platform only and does not guarantee work, customers, bookings or earnings.",
      "By subscribing, Professionals acknowledge and agree that subscription payments are non-refundable, except where required by law. Access is granted for the duration of the paid billing cycle, approximately 30 days per period.",
    ],
  },
  {
    title: "4. Marketplace",
    paragraphs: [
      "SelfeConnect operates solely as an online marketplace where Customers and Professionals may find and communicate with each other. All agreements, pricing, and services are arranged directly between Customers and Professionals.",
      "SelfeConnect does not process payments for services between users and is not involved in any financial transaction between them.",
    ],
  },
  {
    title: "5. No Guarantee of Work",
    paragraphs: [
      "SelfeConnect does not guarantee job opportunities, applications, bookings, agreements, income, earnings, availability of Professionals, response times, or business success.",
    ],
  },
  {
    title: "6. Professional Verification",
    paragraphs: [
      "SelfeConnect does not routinely verify identity, qualifications, licences, insurance, certifications, experience or criminal background. Customers are responsible for performing their own due diligence before engaging any Professional.",
    ],
  },
  {
    title: "7. Stripe Connect, QR Code & Payments",
    paragraphs: [
      "Professionals may connect a Stripe account through Stripe Connect in order to receive payments and voluntary tips from their own customers. SelfeConnect does not process, hold, manage, or control any payments made through Stripe or via QR code links generated by the platform.",
      "All payments made via QR code, Apple Pay, Google Pay, or card payments are processed directly by Stripe and paid directly into the Professional's connected Stripe account, subject to Stripe's own terms and conditions.",
      "SelfeConnect is not a payment provider, money transmitter, financial institution, or payment facilitator. Professionals are solely responsible for complying with Stripe's terms and requirements.",
    ],
  },
  {
    title: "8. Stripe Fees",
    paragraphs: [
      "Stripe may charge transaction fees for payments processed through QR codes or Stripe Connect, typically around 1.5 percent plus 0.20 pounds per transaction depending on region and account type.",
      "These fees are set and collected by Stripe and are not controlled by SelfeConnect. Professionals are responsible for reviewing Stripe's current pricing and fee structure directly with Stripe.",
    ],
  },
  {
    title: "9. Professional Dashboard, QR Code & Marketing Materials",
    paragraphs: [
      "Upon subscription, Professionals are granted access to a personal dashboard. The dashboard may include a unique personal QR code linked to their Stripe account, the ability to accept card payments, Apple Pay and Google Pay via Stripe, and a downloadable flyer or leaflet containing their QR code for offline use.",
      "Professionals may use these materials in physical or digital environments to receive payments or voluntary tips directly from their customers. Customers may also use the QR code to leave reviews and optional tips, where supported by Stripe functionality.",
    ],
  },
  {
    title: "10. Ratings & Reviews",
    paragraphs: [
      "Reviews reflect the opinions of their authors. Users are solely responsible for the content they publish.",
      "SelfeConnect may remove content that is unlawful, abusive, misleading, fraudulent, or inappropriate. SelfeConnect is not responsible for any user-generated content, including reviews and ratings.",
    ],
  },
  {
    title: "11. User Responsibilities",
    paragraphs: [
      "Users must provide accurate and lawful information. Users agree not to create fake accounts or impersonate others, post fake reviews or misleading content, misuse the platform or attempt to bypass its systems, or commit fraud or unlawful activity.",
      "Users must comply with all applicable laws when using the platform.",
    ],
  },
  {
    title: "12. Independent Relationship",
    paragraphs: [
      "Professionals operate as independent businesses. Nothing in these Terms creates an employment, agency, partnership, or joint venture relationship between SelfeConnect and any user.",
    ],
  },
  {
    title: "13. Suspension & Termination",
    paragraphs: [
      "SelfeConnect may suspend or terminate accounts that violate these Terms or engage in harmful, fraudulent, or illegal activity.",
    ],
  },
  {
    title: "14. Intellectual Property",
    paragraphs: [
      "All platform software, branding, logos, and content remain the property of SelfeConnect. Users may not copy, reproduce, or distribute any part of the platform without permission.",
    ],
  },
  {
    title: "15. Disclaimer",
    paragraphs: [
      "SelfeConnect only provides the technology platform. SelfeConnect is not responsible for quality of work, disputes between users, payments between users, cancellations, injuries or damages, fraud or misconduct by users, or agreements made between Customers and Professionals.",
    ],
  },
  {
    title: "16. Limitation of Liability",
    paragraphs: [
      'The platform is provided "as is" and "as available". To the fullest extent permitted by law, SelfeConnect shall not be liable for any indirect, incidental, or consequential damages.',
      "Total liability of SelfeConnect shall not exceed the subscription fees paid by the affected user during the previous 12 months, except where prohibited by law.",
    ],
  },
  {
    title: "17. Changes to Terms",
    paragraphs: [
      "We may update these Terms at any time. Continued use of the platform after changes constitutes acceptance of the updated Terms.",
    ],
  },
  {
    title: "18. Reviews & Account Data After Cancellation",
    paragraphs: [
      "If a Professional cancels their subscription, their profile may be deactivated or removed from the platform. In such cases, reviews and ratings associated with the Professional may no longer be publicly visible or retained on the platform.",
      "If a Professional later rejoins SelfeConnect, they must create a new profile and rebuild their reputation and review history.",
    ],
  },
  {
    title: "19. Governing Law",
    paragraphs: [
      "These Terms are governed by the laws of England and Wales. The courts of England and Wales shall have exclusive jurisdiction over any disputes.",
    ],
  },
];

function Terms() {
  return (
    <main className="min-h-screen bg-background">
      <header className="border-b border-border/60">
        <div className="mx-auto flex max-w-3xl items-center gap-2 px-6 py-4">
          <Link to="/" className="flex items-center gap-2">
            <LogoMark className="h-8 w-8" />
            <span className="font-display font-bold tracking-tight text-foreground">
              SelfeConnect
            </span>
          </Link>
        </div>
      </header>

      <article className="mx-auto max-w-3xl px-6 py-10">
        <h1 className="text-3xl font-bold text-foreground font-display">
          Terms &amp; Conditions
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: 24 July 2026
        </p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-foreground/90">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="text-lg font-semibold">{s.title}</h2>
              {s.paragraphs.map((para, i) => (
                <p key={i} className="mt-2">
                  {para}
                </p>
              ))}
            </section>
          ))}

          <section>
            <h2 className="text-lg font-semibold">20. Contact Us</h2>
            <p className="mt-2">
              Email:{" "}
              <a
                className="text-primary underline"
                href="mailto:support@selfeconnect.com"
              >
                support@selfeconnect.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-10 flex gap-4 text-sm">
          <Link to="/privacy" className="text-primary underline">
            Privacy Policy
          </Link>
          <Link to="/" className="text-muted-foreground underline">
            Back to home
          </Link>
        </div>
      </article>
    </main>
  );
}
