/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostAJobRouteImport } from './routes/post-a-job'
import { Route as MyJobsRouteImport } from './routes/my-jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TipDriverIdRouteImport } from './routes/tip.$driverId'
import { Route as CustomerSignupRouteImport } from './routes/customer.signup'
import { Route as CustomerSearchRouteImport } from './routes/customer.search'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as CustomerAccountRouteImport } from './routes/customer.account'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as TipDriverIdIndexRouteImport } from './routes/tip.$driverId.index'
import { Route as TipDriverIdSuccessRouteImport } from './routes/tip.$driverId.success'
import { Route as CustomerProsPublicIdRouteImport } from './routes/customer.pros.$publicId'
import { Route as CustomerJobsNewRouteImport } from './routes/customer.jobs.new'
import { Route as CustomerJobsJobIdEditRouteImport } from './routes/customer.jobs.$jobId.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAJobRoute = PostAJobRouteImport.update({
  id: '/post-a-job',
  path: '/post-a-job',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsRoute = MyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TipDriverIdRoute = TipDriverIdRouteImport.update({
  id: '/tip/$driverId',
  path: '/tip/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer/signup',
  path: '/customer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSearchRoute = CustomerSearchRouteImport.update({
  id: '/customer/search',
  path: '/customer/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAccountRoute = CustomerAccountRouteImport.update({
  id: '/customer/account',
  path: '/customer/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const TipDriverIdIndexRoute = TipDriverIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TipDriverIdRoute,
} as any)
const TipDriverIdSuccessRoute = TipDriverIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => TipDriverIdRoute,
} as any)
const CustomerProsPublicIdRoute = CustomerProsPublicIdRouteImport.update({
  id: '/customer/pros/$publicId',
  path: '/customer/pros/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerJobsNewRoute = CustomerJobsNewRouteImport.update({
  id: '/customer/jobs/new',
  path: '/customer/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerJobsJobIdEditRoute = CustomerJobsJobIdEditRouteImport.update({
  id: '/customer/jobs/$jobId/edit',
  path: '/customer/jobs/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-a-job': typeof PostAJobRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/tip/$driverId': typeof TipDriverIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/jobs/new': typeof CustomerJobsNewRoute
  '/customer/pros/$publicId': typeof CustomerProsPublicIdRoute
  '/tip/$driverId/success': typeof TipDriverIdSuccessRoute
  '/tip/$driverId/': typeof TipDriverIdIndexRoute
  '/customer/jobs/$jobId/edit': typeof CustomerJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-a-job': typeof PostAJobRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/jobs/new': typeof CustomerJobsNewRoute
  '/customer/pros/$publicId': typeof CustomerProsPublicIdRoute
  '/tip/$driverId/success': typeof TipDriverIdSuccessRoute
  '/tip/$driverId': typeof TipDriverIdIndexRoute
  '/customer/jobs/$jobId/edit': typeof CustomerJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-a-job': typeof PostAJobRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/tip/$driverId': typeof TipDriverIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/jobs/new': typeof CustomerJobsNewRoute
  '/customer/pros/$publicId': typeof CustomerProsPublicIdRoute
  '/tip/$driverId/success': typeof TipDriverIdSuccessRoute
  '/tip/$driverId/': typeof TipDriverIdIndexRoute
  '/customer/jobs/$jobId/edit': typeof CustomerJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/my-jobs'
    | '/post-a-job'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/terms'
    | '/unsubscribe'
    | '/verify'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/jobs'
    | '/admin/quotes'
    | '/admin/reviews'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/verifications'
    | '/customer/account'
    | '/customer/login'
    | '/customer/search'
    | '/customer/signup'
    | '/tip/$driverId'
    | '/admin/'
    | '/customer/'
    | '/customer/jobs/new'
    | '/customer/pros/$publicId'
    | '/tip/$driverId/success'
    | '/tip/$driverId/'
    | '/customer/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/my-jobs'
    | '/post-a-job'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/terms'
    | '/unsubscribe'
    | '/verify'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/jobs'
    | '/admin/quotes'
    | '/admin/reviews'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/verifications'
    | '/customer/account'
    | '/customer/login'
    | '/customer/search'
    | '/customer/signup'
    | '/admin'
    | '/customer'
    | '/customer/jobs/new'
    | '/customer/pros/$publicId'
    | '/tip/$driverId/success'
    | '/tip/$driverId'
    | '/customer/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/my-jobs'
    | '/post-a-job'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/terms'
    | '/unsubscribe'
    | '/verify'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/jobs'
    | '/admin/quotes'
    | '/admin/reviews'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/verifications'
    | '/customer/account'
    | '/customer/login'
    | '/customer/search'
    | '/customer/signup'
    | '/tip/$driverId'
    | '/admin/'
    | '/customer/'
    | '/customer/jobs/new'
    | '/customer/pros/$publicId'
    | '/tip/$driverId/success'
    | '/tip/$driverId/'
    | '/customer/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  MyJobsRoute: typeof MyJobsRoute
  PostAJobRoute: typeof PostAJobRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyRoute: typeof VerifyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CustomerAccountRoute: typeof CustomerAccountRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerSearchRoute: typeof CustomerSearchRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  TipDriverIdRoute: typeof TipDriverIdRouteWithChildren
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerJobsNewRoute: typeof CustomerJobsNewRoute
  CustomerProsPublicIdRoute: typeof CustomerProsPublicIdRoute
  CustomerJobsJobIdEditRoute: typeof CustomerJobsJobIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-a-job': {
      id: '/post-a-job'
      path: '/post-a-job'
      fullPath: '/post-a-job'
      preLoaderRoute: typeof PostAJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs': {
      id: '/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof MyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tip/$driverId': {
      id: '/tip/$driverId'
      path: '/tip/$driverId'
      fullPath: '/tip/$driverId'
      preLoaderRoute: typeof TipDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signup': {
      id: '/customer/signup'
      path: '/customer/signup'
      fullPath: '/customer/signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/search': {
      id: '/customer/search'
      path: '/customer/search'
      fullPath: '/customer/search'
      preLoaderRoute: typeof CustomerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/account': {
      id: '/customer/account'
      path: '/customer/account'
      fullPath: '/customer/account'
      preLoaderRoute: typeof CustomerAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tip/$driverId/': {
      id: '/tip/$driverId/'
      path: '/'
      fullPath: '/tip/$driverId/'
      preLoaderRoute: typeof TipDriverIdIndexRouteImport
      parentRoute: typeof TipDriverIdRoute
    }
    '/tip/$driverId/success': {
      id: '/tip/$driverId/success'
      path: '/success'
      fullPath: '/tip/$driverId/success'
      preLoaderRoute: typeof TipDriverIdSuccessRouteImport
      parentRoute: typeof TipDriverIdRoute
    }
    '/customer/pros/$publicId': {
      id: '/customer/pros/$publicId'
      path: '/customer/pros/$publicId'
      fullPath: '/customer/pros/$publicId'
      preLoaderRoute: typeof CustomerProsPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/jobs/new': {
      id: '/customer/jobs/new'
      path: '/customer/jobs/new'
      fullPath: '/customer/jobs/new'
      preLoaderRoute: typeof CustomerJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/jobs/$jobId/edit': {
      id: '/customer/jobs/$jobId/edit'
      path: '/customer/jobs/$jobId/edit'
      fullPath: '/customer/jobs/$jobId/edit'
      preLoaderRoute: typeof CustomerJobsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TipDriverIdRouteChildren {
  TipDriverIdSuccessRoute: typeof TipDriverIdSuccessRoute
  TipDriverIdIndexRoute: typeof TipDriverIdIndexRoute
}

const TipDriverIdRouteChildren: TipDriverIdRouteChildren = {
  TipDriverIdSuccessRoute: TipDriverIdSuccessRoute,
  TipDriverIdIndexRoute: TipDriverIdIndexRoute,
}

const TipDriverIdRouteWithChildren = TipDriverIdRoute._addFileChildren(
  TipDriverIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  MyJobsRoute: MyJobsRoute,
  PostAJobRoute: PostAJobRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyRoute: VerifyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CustomerAccountRoute: CustomerAccountRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerSearchRoute: CustomerSearchRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  TipDriverIdRoute: TipDriverIdRouteWithChildren,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerJobsNewRoute: CustomerJobsNewRoute,
  CustomerProsPublicIdRoute: CustomerProsPublicIdRoute,
  CustomerJobsJobIdEditRoute: CustomerJobsJobIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
