/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TipDriverIdRouteImport } from './routes/tip.$driverId'
import { Route as CustomerSignupRouteImport } from './routes/customer.signup'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as TipDriverIdIndexRouteImport } from './routes/tip.$driverId.index'
import { Route as TipDriverIdSuccessRouteImport } from './routes/tip.$driverId.success'
import { Route as CustomerJobsNewRouteImport } from './routes/customer.jobs.new'
import { Route as CustomerJobsJobIdEditRouteImport } from './routes/customer.jobs.$jobId.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TipDriverIdRoute = TipDriverIdRouteImport.update({
  id: '/tip/$driverId',
  path: '/tip/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer/signup',
  path: '/customer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const TipDriverIdIndexRoute = TipDriverIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TipDriverIdRoute,
} as any)
const TipDriverIdSuccessRoute = TipDriverIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => TipDriverIdRoute,
} as any)
const CustomerJobsNewRoute = CustomerJobsNewRouteImport.update({
  id: '/customer/jobs/new',
  path: '/customer/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerJobsJobIdEditRoute = CustomerJobsJobIdEditRouteImport.update({
  id: '/customer/jobs/$jobId/edit',
  path: '/customer/jobs/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/tip/$driverId': typeof TipDriverIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/jobs/new': typeof CustomerJobsNewRoute
  '/tip/$driverId/success': typeof TipDriverIdSuccessRoute
  '/tip/$driverId/': typeof TipDriverIdIndexRoute
  '/customer/jobs/$jobId/edit': typeof CustomerJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/jobs/new': typeof CustomerJobsNewRoute
  '/tip/$driverId/success': typeof TipDriverIdSuccessRoute
  '/tip/$driverId': typeof TipDriverIdIndexRoute
  '/customer/jobs/$jobId/edit': typeof CustomerJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/tip/$driverId': typeof TipDriverIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/jobs/new': typeof CustomerJobsNewRoute
  '/tip/$driverId/success': typeof TipDriverIdSuccessRoute
  '/tip/$driverId/': typeof TipDriverIdIndexRoute
  '/customer/jobs/$jobId/edit': typeof CustomerJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/admin/drivers'
    | '/admin/transactions'
    | '/customer/login'
    | '/customer/signup'
    | '/tip/$driverId'
    | '/admin/'
    | '/customer/'
    | '/customer/jobs/new'
    | '/tip/$driverId/success'
    | '/tip/$driverId/'
    | '/customer/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/admin/drivers'
    | '/admin/transactions'
    | '/customer/login'
    | '/customer/signup'
    | '/admin'
    | '/customer'
    | '/customer/jobs/new'
    | '/tip/$driverId/success'
    | '/tip/$driverId'
    | '/customer/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/admin/drivers'
    | '/admin/transactions'
    | '/customer/login'
    | '/customer/signup'
    | '/tip/$driverId'
    | '/admin/'
    | '/customer/'
    | '/customer/jobs/new'
    | '/tip/$driverId/success'
    | '/tip/$driverId/'
    | '/customer/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  TipDriverIdRoute: typeof TipDriverIdRouteWithChildren
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerJobsNewRoute: typeof CustomerJobsNewRoute
  CustomerJobsJobIdEditRoute: typeof CustomerJobsJobIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tip/$driverId': {
      id: '/tip/$driverId'
      path: '/tip/$driverId'
      fullPath: '/tip/$driverId'
      preLoaderRoute: typeof TipDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signup': {
      id: '/customer/signup'
      path: '/customer/signup'
      fullPath: '/customer/signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tip/$driverId/': {
      id: '/tip/$driverId/'
      path: '/'
      fullPath: '/tip/$driverId/'
      preLoaderRoute: typeof TipDriverIdIndexRouteImport
      parentRoute: typeof TipDriverIdRoute
    }
    '/tip/$driverId/success': {
      id: '/tip/$driverId/success'
      path: '/success'
      fullPath: '/tip/$driverId/success'
      preLoaderRoute: typeof TipDriverIdSuccessRouteImport
      parentRoute: typeof TipDriverIdRoute
    }
    '/customer/jobs/new': {
      id: '/customer/jobs/new'
      path: '/customer/jobs/new'
      fullPath: '/customer/jobs/new'
      preLoaderRoute: typeof CustomerJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/jobs/$jobId/edit': {
      id: '/customer/jobs/$jobId/edit'
      path: '/customer/jobs/$jobId/edit'
      fullPath: '/customer/jobs/$jobId/edit'
      preLoaderRoute: typeof CustomerJobsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDriversRoute: typeof AdminDriversRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDriversRoute: AdminDriversRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TipDriverIdRouteChildren {
  TipDriverIdSuccessRoute: typeof TipDriverIdSuccessRoute
  TipDriverIdIndexRoute: typeof TipDriverIdIndexRoute
}

const TipDriverIdRouteChildren: TipDriverIdRouteChildren = {
  TipDriverIdSuccessRoute: TipDriverIdSuccessRoute,
  TipDriverIdIndexRoute: TipDriverIdIndexRoute,
}

const TipDriverIdRouteWithChildren = TipDriverIdRoute._addFileChildren(
  TipDriverIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  TipDriverIdRoute: TipDriverIdRouteWithChildren,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerJobsNewRoute: CustomerJobsNewRoute,
  CustomerJobsJobIdEditRoute: CustomerJobsJobIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
